apiVersion: v1
kind: Pod
metadata:
  name: blue-green
spec:
  containers:
    - name: blue-green
      image: mtinside/blue-green:blue
      resources:
        requests:
          memory: "64Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
